### ISSUE TITLE
cmd Config must write default values to cfg

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#25]
Плаги так делают- метод Config сначал пишет текущие опции в файл, а потом открывает файл.
так юзер увидит все  опции в файле

В куд лучше юзать ini_read(), ini_write()

**Comment by viad00** [comment]
Т.е. надо писать в user.json значения по умолчанию? Зачем тогда ini, если вся настройка идёт через json

**Comment by Alexey-T** [comment]
сори, запутал. Забыл как мы хотели сначала.
