### ISSUE TITLE
too early cancelling

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#32]
```
 begin
  fLastError := AErrorID; // dummy stub - useless because will raise exception
  if AErrorID < 1000 // compilation error ?
   then e := ERegExpr.Create (ErrorMsg (AErrorID) // yes - show error pos
             + ' (pos ' + IntToStr (CompilerErrorPos) + ')')
   else e := ERegExpr.Create (ErrorMsg (AErrorID));
  e.ErrorCode := AErrorID;
  e.CompilerErrorPos := CompilerErrorPos;
  raise e
   {$IFDEF reRealExceptionAddr}
   At ReturnAddr; //###0.938
   {$ENDIF}
 end; { of procedure TRegExpr.Error
--------------------------------------------------------------}
```
кликаю тут в разные места чтобы проверить что плаг найдет и посветит.
но если кликать после концов - или в {$ifdef } - то плаг вырубается

**Comment by viad00** [comment]
У меня то что внутри дефайна обрабатывается нормально, сами дефайны не являются id, у них тип preprocessor
![image](https://user-images.githubusercontent.com/16987973/43689295-044f38e0-9901-11e8-913c-bc8d658ba313.png)

**Comment by Alexey-T** [comment]
ну при клике (после концов или в Ifdef) надо не ресетить, а оставлять подсветку блока, тоько стопить правку текущего слова.

**Comment by Alexey-T** [comment]
т е как в Сине.

**Comment by Alexey-T** [comment]
стало лучше.
