### ISSUE TITLE
optim

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#35]
first_y = ed_self.get_carets()[0][1]
        first_x = ed_self.get_carets()[0][0]

обычно пишу так-
```
carets = ed.get_carets()
if len(carets)!=1:
  msg_status('Cannot work with multi-carets')
  return
x, y, x1, y1 = carets[0]
```

**Comment by Alexey-T** [comment]
first_caret = ed_self.get_carets()[0]
            if first_caret[1] > self.start or first_caret[3] > self.end or first_caret[1] < self.start:

это тоже красивее будет.

x, y, x1, y1 = carets[0]
if  y>self.start or y1>self.end or y<self.start

**Comment by Alexey-T** [comment]
первый пост- не поправлено.
```
carets = ed.get_carets()
if len(carets)!=1:
  msg_status('Cannot work with multi-carets')
  return
x, y, x1, y1 = carets[0]
```

**Comment by viad00** [comment]
2 строки выше:
```
        # Find out what changed on the first caret (on others changes will be the same)
        old_key = self.our_key
        self.our_key = None
        first_y = ed_self.get_carets()[0][1]
        first_x = ed_self.get_carets()[0][0]
```
т.е. этот код работает (и должен работать) и с мультикаретками
