### ISSUE TITLE
editing doesnot activate sometimes

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#41]
из такого состояния
![screenshot from 2018-08-06 11-35-48](https://user-images.githubusercontent.com/4154978/43706066-00e16838-996d-11e8-9bbd-228d159b7257.png)

кликаю слово Create левее. и режим активный пропадает- просто каретка переносится на слово create. надо чтобы был активный режим с "create".

**Comment by Alexey-T** [comment]
тоже самое если при правке MARKERS_BORDER_COLOR
кликнуть на слове MARKERS_ADD.
```
        ed_self.attr(MARKERS_DELETE_BY_TAG, tag=MARKER_CODE)
        for key_tuple in self.dictionary[self.our_key]:
                ed_self.attr(MARKERS_ADD, tag = MARKER_CODE, \
                x = key_tuple[0][0], y = key_tuple[0][1], \
                len = key_tuple[1][0] - key_tuple[0][0], \
                color_bg=MARKER_BG_COLOR, color_border=MARKER_BORDER_COLOR, \
                border_left=1, border_right=1, border_down=1, border_up=1)
```

**Comment by viad00** [comment]
Переход на на новое слово подразумевает выход из режима редактирования. Т.е. нажимаем вне изменяемой области - выход из режима, подсветка идентификаторов. Затем нажимаем на то что надо отредактировать теперь

**Comment by Alexey-T** [comment]
Хм. Синрайт дает кликать все слова в нашем блоке и так можно менять их все за один раз

@kvichans может вам интересно протестить?

**Comment by Alexey-T** [comment]
@olehl @iramsoft может хотите протестить.

**Comment by Alexey-T** [comment]
посмотри, разве в Сине не удобно кликать другое слово и сразу править его?

**Comment by iRamSoft** [comment]
В Сине было удобно, и очень часто этим пользовался. А вот в Cuda этого не стало.

Это в офф сборке ещё нет? Только в гите?

**Comment by Alexey-T** [comment]
@iramsoft Надо ставить плаг из гитхаб-
Plugins / AddonManager / Install from github
а потом репортить недочеты
