### ISSUE TITLE
slow activating of plugin

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#43]
может это мое АПИ тормозит? активация плагина на теле ф-ции из конца файла regexpr.pas- пауза 1-2 сек.

**Comment by viad00** [comment]
Подозреваю это из-за lexer_scan в начале активации, я изменил сканирование с первой строчки на начало выделения, теперь работает быстрее (у меня в районе 300мс в regexpr.pas).

**Comment by viad00** [comment]
Если сильно тормозит можно вообще отказаться, правда тогда не факт что в момент включения плагина произошло сканирование.

**Comment by Alexey-T** [comment]
Вроде стало хорошо

**Comment by Alexey-T** [comment]
@kvichans может вам интересен этот плагин.

**Comment by kvichans** [comment]
До конца недели не смогу проверить
