### ISSUE TITLE
Show progressbar

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#46]
Можеш показать прогрессбар - чтобы видно что плаг не завис на _всем_ выделенном regexpr.pas?

app_proc(PROC_PROGGRESSBAR, n)
и потом спрятать.

**Comment by viad00** [comment]
Код добавил, однако куда не рендерит прогрессбар во время выполнения кода плагина, так что видимости прогресса никакой

**Comment by Alexey-T** [comment]
хм. Тогда надо вызвать application.processmesssages-

app_idle(??)

**Comment by Alexey-T** [comment]
можеш сделать функцию с параметром инт? В ней же юзать appidle
