### ISSUE TITLE
invert_color for blue

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#58]
@iRamSoft синий странно инверснулся.
![screenshot from 2018-08-07 15-35-07](https://user-images.githubusercontent.com/4154978/43776164-ab3370e8-9a57-11e8-83c8-20126d64e628.png)

тема sub.

**Comment by iRamSoft** [comment]
А такая офигенная задумка была. Вот только синий мне не попадался.

**Comment by Alexey-T** [comment]
Можеш подстроить фцию?

**Comment by iRamSoft** [comment]
Сейчас постараюсь
