### ISSUE TITLE
for Markdown etc

### ISSUE THREAD

**Issue by MiroslavMatas** [viad00/cuda_sync_editing#63]
first of all - I very appreciate that plugin, so please do not take my comment as critique… I want to help
but current configuration is very complicated, seems to me
I was not able to configure it for "lexer none". Is that possible?
from my point of view - will be better to deliver some minimal default configuration - like: case sensitive true for all lexers + syncedit_mark_words to true 
I am not able to copy/paste from dialog Sync Editor Config - what is ok, but… do we have a way how to copy/paste possible options? (search on files works for me, but it is not so user friendly…) what about list of options at Readme? (+ what option to what file)
even spending some time on that, it not works for me on Markdown lexer (as example)

**Comment by Alexey-T** [comment]
Plugin needs improving for
- none lexer
- Markdown lexer

now it finds IDs by lexer style "Id", it is not so for none/markdown lexer.

**Comment by Alexey-T** [comment]
@MiroslavMatas Try plugin from Github (AddonManager - install from Github)
it must work OK for Markdown and none lexer. Ok?

**Comment by Alexey-T** [comment]
plugin updated in AddonManager

**Comment by MiroslavMatas** [comment]
brilliant!

**Comment by Alexey-T** [comment]
@MiroslavMatas Can you help to update  CZ and/or Slovak translations to last app?
https://sourceforge.net/projects/cudatext/files/addons/translations/

**Comment by MiroslavMatas** [comment]
I start to work on that, right now approx 50% is done.Will you update later, I will try to finish as soon as possible…Than I will open Slovak translattion.
Miro
