### ISSUE TITLE
last patch not correct

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#64]
1) Afaik, STYLES_DEFAULT (+_NO) это были дефолты для опций- а сами опции это STYLES, STYLES_NO.
а пач делает присваивание STYLES_DEFAULT.
нелзя.

2) зачем NON_STANDARD_LEXERS, разве нельзя уже задать все стили через опции- которые ставят STYLES, STYLES_NO?

**Comment by Alexey-T** [comment]
2б. Для markdown например ты можешь уже задать стили любые.

**Comment by viad00** [comment]
1. Патч добавляет возможность работать из коробки с тем с чем плагин не будет работать по дефолту, возможность пользовательских настроек сохранена, ведь юзеру может понадобиться другое поведение, в дальнейшем его можно расширить и на другие языки. Присваивание идёт до чтения настроек, что позволяет в любом случае применить пользовательские настройки, иначе он присвоит в любом случае пользовательские, если их нет то дефолт, а дефолт не нужен, нужен не стандартный дефолт.
2. При необходимости можно добавить и для STYLES_NO, по аналогии, однако я пока не встретил поведения, где оно понадобиться, для php и markdown они не потребовались.
2б. Возможность установки своих настроек сохранена.

**Comment by Alexey-T** [comment]
Проверю работу тогда.
