### ISSUE TITLE
Broken hilite of active words

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#65]
example file
```
test aa test aa
test aa test aa
test aa test aa
test aa test aa
```
i click middle of word "test" and move lefter and add "zz".
--> hiliting of all active words broken

![screenshot from 2018-08-26 00-25-20](https://user-images.githubusercontent.com/4154978/44622708-b9dc1780-a8c6-11e8-9f1b-285a01b5ea71.png)

**Comment by Alexey-T** [comment]
same bug if I call Markdown for this test.

**Comment by Alexey-T** [comment]
недофиксено.
при старте 

 
![screenshot from 2018-08-26 23-22-00](https://user-images.githubusercontent.com/4154978/44632644-de97c400-a986-11e8-912a-23cd263fe586.png)

после вставки "222" в слове

![screenshot from 2018-08-26 23-20-59](https://user-images.githubusercontent.com/4154978/44632636-c3c54f80-a986-11e8-861d-85ee793ebed8.png)

**Comment by Alexey-T** [comment]
Кстати, гх не показывает что ты чтото сделал- пока ты не закрыл или пока не написал коммент

**Comment by viad00** [comment]
Странно, я был уверен что уже изменял regex из-за которого это происходило.

**Comment by Alexey-T** [comment]
а я менял потом.
