### ISSUE TITLE
need fix for REST

### ISSUE THREAD

**Issue by Alexey-T** [viad00/cuda_sync_editing#66]
reStructuredText (lexer like Markdown)
Textile (too, lexer in AddonManager)

тут плаг берет одну букву - в слове  tttttt он выделяет 6 блоков.

**Comment by viad00** [comment]
Я добавил настройку для наивного алгоритма, думаю что это самое то для языков облегчённой разметки.

**Comment by Alexey-T** [comment]
я уже поправил сам лексер reST + plugin.
