### ISSUE TITLE
[feature] Allow hotkey to pick an identifier not just via mouse click

### ISSUE THREAD

**Issue by WebMechanic** [viad00/cuda_sync_editing#68]
Hi,

I am new to CudaText and found your plugin which is great! I use similar features in VSCode and WebStorm.

However, the requirement to reach for the mouse, when I am actually with all hands on the keyboard and then *click* on an identifier to perform the rename is a bit counter productive.
Also for people than can't utilize a mouse or depend on keyboard only input this plugin is not useful and accessible.

May you can add a keyboard listener with a customizable hotkey that does the same if the text input cursor in inside the bounds of a identifier. OR maybe there is and it's just not prominently documented :D

This way one could select the line with the keyboard, activate the plugin with a hotkey, navigate with the cursor to the identifier, press another "edit" hotkey, and be done. No mouse involved

- VSCode offers F2 to rename "symbols"
- WebStorm has "Shift-F6" to rename "code occurances" within

Thanks for considering!

**Comment by Alexey-T** [comment]
Plugin is updated, added the new command to 'emulate click', you can assign any hotkey to it in the CommandPalette.

**Comment by Alexey-T** [comment]
Updated again.

**Comment by WebMechanic** [comment]
Hey,
thanks for the feature update!

There's an issue with the input cursor if I enable the sync edit using keyboard shortcuts.
It also has troubles detecting diacritic characters such as umlauts, possibly others.

Here's what I did in the recording below (proper .html file). No mouse involved.
- select the lines with shift+down-arrow
- press assigned hotkey to activate sync editing; **it initially ignores the umlaut Ü**
- _cursor jumps to the beginning of the file_
- navigate back to the selected area
- press assigned new hotkey (F2) to pick the identifier, the letter Ü is clearly not detected
- _move input cursor_ anywhere inside the identifier (left arrow): the "Ü" now becomes part of the identifier and all can be edited ( I actually forgot to record that, but it works)

> I'm aware that I could just use a simple block selection in this particular example.

![cuda-sync-edit_01](https://user-images.githubusercontent.com/638340/146672839-6bd7cab4-5c9c-4e3a-8a5c-cd27a958df34.gif)

I like that I can also deactivate by pressing that "F2" again and don't need another hotkey. It's just like clicking outside the area of marked identifiers! 👍🏻

It does not seem to work in Markdown files at all using either method to activate it.
Activating the plugin with the hotkey simply undoes the selection and also places the cursor at the beginning of the file.

I had actually expected the h1, h2, etc. pairs (see below) to also become editable identifiers, so I could edit each of their opening and closing tags. So I tested some other area in the HTML.

If the selection contains html elements only it also does nothing but clears the selection and places the cursor to the first line. For this one I used only the mouse, however you can't see me picking the menu command to activate the plugin. Again, the selection is cleared and the cursor placed at the beginning of the file.

![cuda-sync-edit_02](https://user-images.githubusercontent.com/638340/146673474-c3cdb7d9-e8d3-4d33-8d6f-3d8315ed8732.gif)

> While it seems to be another case for a simple block selection, moving multiple cursors with Ctrl+Arrow would unsync the cursor positions _at the hyphen_ in "fonts-league" as a word boundary in order to get to the ".css" and change them.

**Comment by Alexey-T** [comment]
1) Made a fix in HTML lexer, get it it
https://github.com/Alexey-T/CudaText/blob/master/app/data/lexlib/HTML.lcf

2) made a fix in plugin to restore caret (after activating). 
get it from this Github repo.
https://github.com/viad00/cuda_sync_editing/blob/master/__init__.py

Is it better in HTML now?

Let's create a new issue about Markdown to not get a mess.

**Comment by Alexey-T** [comment]
(post a sample Markdown file to the new issue)

**Comment by Alexey-T** [comment]
>While it seems to be another case for a simple block selection, moving multiple cursors with Ctrl+Arrow would unsync the cursor positions at the hyphen in "fonts-league" as a word boundary 

This needs the changed option of plugin. see "Options / Settings-plugins / Sync Editing". Try to write the proper RegEx for HTML names with '-'. 

And it needs change of another option! Name of 'lexer rule' to catch by Sync Editing.

Does it help?

**Comment by Alexey-T** [comment]
![Screenshot from 2021-12-19 15-31-13](https://user-images.githubusercontent.com/4154978/146674936-27e155f6-37b3-4ccd-9f35-7f92a53c7d27.png)

**Comment by WebMechanic** [comment]
> This needs the changed option of plugin. see "Options / Settings-plugins / Sync Editing". Try to write the proper RegEx for HTML names with '-'.

This was unrelated to the sync plugin or any lexer.
In general moving cursors with Ctrl+Arrow jumps to the next word boundary, and that's expected and well-known behaviour **in all apps**. It's nothing a global setting would fix and it's not related to nor a "bug" of any language lexer. In most cases that's exactly what you want and expect to happen (jump to word boundaries), but occasionally it fails you; like in this case.

That's why the sync editing would be the better tool in such cases: I could "pick" the identifier string `css` and change it to `scss`.

**Comment by WebMechanic** [comment]
> Is it better in HTML now?

Partially.

The cursor now jumps back to where it was when the selection was made, 👍🏻
but the selection just cleared and there are no identifiers. 
You can check with any simple,  vanilla HTML (or Markdown for that matter.)

**Comment by Alexey-T** [comment]
I found how to work with HTML/Markdown. wrote new text to plugin's readme.
Confirm it's OK for you?
```

Lexers HTML and Markdown
------------------------

By default, plugin don't support lexer HTML and Markdown, but this can be customized.
1) HTML.
Open HTML-specific config file: activate HTML lexer, call "Options / Settings - lexer specific".
File "settings/lexer HTML.json" will be opened. Write there:

  "id_styles": "Tag id correct",

Now plugin must detect tag-names as IDs, and must allow to rename them.
To detect also tag properties as IDs, write:

  "id_styles": "Tag id correct|Tag prop",

2) Markdown.
By default, plugin cannot detect separate words in Markdown.
Open Markdown-specific config, file "settings/lexer Markdown.json". Write there:

  "syncedit_naive_mode": true,
```

**Comment by WebMechanic** [comment]
I don't know how to access that dialog box nor where that information comes from. 
There is no evident feature in the UI that would bring up anything like this.

**Comment by Alexey-T** [comment]
Pls see my previous reply

**Comment by WebMechanic** [comment]
it popped up when I was submitting mine .. pls give me some time to read and consume it :)

**Comment by WebMechanic** [comment]
`"syncedit_naive_mode": true` did the trick for Markdown, 👍🏻

but I have no clue what the other stuff means or what I'm supposed to enter there  `"Tag id correct"` ?? 😲 Do I just copy this?

**Comment by WebMechanic** [comment]
ok I just copied it, and it does mark tag names and attributes. Nice!

However, it (still) ignores the **attribute values** which would be equally interesting and useful to sync edit, i.e from the GIF above the string/word "css" is repetitive, so it should/would be a candidate for an identifier, no?

**Comment by Alexey-T** [comment]
>but I have no clue what the other stuff means or what I'm supposed to enter there "Tag id correct" ??

for Markdown, only the line "syncedit_naive_mode" is needed, others are not needed.

**Comment by Alexey-T** [comment]
>However, it (still) ignores the attribute values which would be equally interesting and useful to sync edit

To detect words inside quotes values, you will need this option (it overrides "id_styles") in HTML specific config:

  "syncedit_naive_mode": true,

does it help?

**Comment by Alexey-T** [comment]
It helps here
![Screenshot from 2021-12-19 16-22-28](https://user-images.githubusercontent.com/4154978/146676358-0cf847cd-7f6c-4c9e-ba29-2da2908e3ca9.png)

**Comment by WebMechanic** [comment]
I copied `"syncedit_naive_mode": true` to the Markdown json: that worked.

I copied `"id_styles": "Tag id correct|Tag prop"` to the HTML  json, and it selects tags and attributes

**EDIT: just saw the "naive mode" for HTML... will give this a try**

**EDIT 2: yep. Attribute-values are now included.**

![image](https://user-images.githubusercontent.com/638340/146677871-206fb449-3233-4c2d-88c8-2a87a29f6ebc.png)

Just curious: what's "naive" about this behaviour? because there's no regex magic involved? 😉😁

**Comment by Alexey-T** [comment]
yep, with 'naive' mode no regex are used. glad it's OK now.

**Comment by WebMechanic** [comment]
**Well done! Thank you!**

I suppose with block selection (multi cursor), search/replace inside selection and sync edit, there are various ways to make granular and specific edits. 👍🏻😎

---
and just for the record: VSCode's "replace in selection" mode is buggy as hell and virtually not functional. So your editor is outsmarting a big player here!!

**Comment by Alexey-T** [comment]
Thanks to @viad00 again. :)

**Comment by Alexey-T** [comment]
@WebMechanic I changed the plugin's presets- now 

```
NON_STANDART_LEXERS = {
  'HTML': 'Text|Tag id correct|Tag prop',
  'PHP': 'Var',
}
  
NAIVE_LEXERS = [
  'Markdown', # it has 'Text' rule for many chars, including punctuation+spaces
  'reStructuredText',
  'Textile',
]
```

and you see I made those settings the new default.
